# Results

## Packages
All packages we have used in this section. 
```{r}
library(dplyr)
library(tidyverse)
library(dygraphs)
library(xts)
```

## Data
Before moving on, let us first draw some insights from each pollutant over the past ten years. 
```{r}
data = read.csv(file='./data/processedData.csv')
data %>% select(TOTAL_SO2, TOTAL_NO3, CA, MG, CL, K) %>% summary()
```

### Data Distributions (SO2 and NO3)

### Data Distributions (CA, MG, CL, K)
```{r}
data$date_off = as.Date(data$date_off)

selected_cols <- c("date_off", "REGION","STATE", "COUNTY","VALID_HOURS","TOTAL_SO2", "TOTAL_NO3", "CA", "MG", "K", "CL")
new_data <- data %>% select(selected_cols)

tidy_data <- pivot_longer(new_data, 
             cols=c("CA", "MG", "K", "CL"),
             names_to = "Pollutant",
             values_to = "Concentration",
             values_drop_na = TRUE)

pollutants <- c("CA", "MG", "K", "CL")

ggplot(tidy_data, aes(x=reorder(Pollutant, -Concentration, median),
                 y = Concentration)) +
  geom_boxplot(fill="lightBlue", color = "#473e2c") +
  coord_flip() + 
  scale_y_log10() +
  facet_grid(rows=vars(REGION))+
  xlab("Pollutant") +
  ylab("Concentration")
```

## How does air pollution spread over the past ten years?

```{r}
national_so2 <- data %>% 
  group_by(date_off) %>% 
  summarise(mean_SO2 = mean(TOTAL_SO2, na.rm=TRUE), .groups='drop') %>% 
  na.omit()

time_series_obj <- xts(x = national_so2$mean_SO2, order.by = national_so2$date_off)
dygraph(time_series_obj,
        main = "Sulfur Dioxide Trend in US",
        xlab = "Date",
        ylab = "SO2 (ug/m^3)") %>% 
  dyRangeSelector()
```

