--- 
title: "EDAV Group3: Air Pollution Over the United States"
author: "Xinwen Miao, Yilan Jiang, Huiqian Yu, Diyue Gu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Air quality is linked to human activities, earth’s climate and ecosystems globally. Air pollution is a mixture of solid particles and gases in the air. Air pollution causes damage to crops, animals, forests and water. Also air pollution exposure is associated with oxidative stress and inflammation in human cells, which may lay a foundation for chronic diseases and cancer. 

Meanwhile, human activities have been highlighted as the major causes of air pollution, especially in the cities. To support a larger population, there's a need for energy production, transportation, and industries, resulting in the emission of harmful chemicals into the atmosphere. 

Air pollution is one of the most serious problems in the world. Therefore, we decide to use exploratory data analysis to study on air pollution across the United States over last 10 years, to figure out the trends of pollutants seasonal and spatial changes, if Covid-19 lockdown significantly reduce air pollution, and connection between air pollution and human health. 

